config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root to: "home#index"
  resources :user do
    resources :party, only: [:index]
  end
  resources :party, except: [:index]
  resources :reservation, only: [:create]
  delete 'reservation', to: 'reservation#destroy'
  post 'guest', to: 'guest#create'
  put 'wish_list_item/:id', to: 'wish_list_item#reserve'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  validates_presence_of :party, :user
  belongs_to :party
  belongs_to :user
end

app/models/party.rb
class Party < ApplicationRecord
  validates_presence_of :user, :date, :title
  belongs_to :user

  def wish_list
    user.wish_list_items
  end

  def on_guest_list?(guest)
    Guest.where(party: id).where(user_id: guest.id).any?
  end
end

app/models/person.rb
class Person < ApplicationRecord
  validates_presence_of :first_name, :last_name, :email
  has_many :parties, class_name: '::Party'
  has_many :wish_list_items, class_name: '::WishListItem'
end

app/models/present.rb
# class Present < ApplicationRecord
#   validates_presence_of :name, :img_url, :user
#   belongs_to :user
# end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates_presence_of :wish_list_item, :user
  belongs_to :wish_list_item
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :first_name, :last_name, :email
  has_many :parties, class_name: '::Party'
  has_many :wish_list_items, class_name: '::WishListItem'
  has_many :guests, class_name: '::Guest'

  def full_name
    "#{first_name} #{last_name}"
  end

  def on_guest_list
    Guest.where(user_id: id)
  end
end

app/models/wish_list_item.rb
class WishListItem < ApplicationRecord
  belongs_to :user
  has_one :reservations, class_name: '::Reservation'
  validates_presence_of :name, :location, :img_url, :price, :user

  def reserved_by
    reservation = Reservation.find_by(wish_list_item_id: id)
    reservation.user if reservation
  end

  def reserved?
    Reservation.where(wish_list_item_id: id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guest_controller.rb
class GuestController < ApplicationController
  before_action :authenticate_user!

  def create
    Guest.create(party: party, user: current_user)
    render "party/show"
  end

  private

  def party
    @party ||= Party.find(attributes[:party_id])
  end

  def attributes
    @attributes ||= params.require(:guest).permit(:party_id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/party_controller.rb
class PartyController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def create
    Party.create(attributes.merge(user: user))
    render 'show'
  end

  def new
  end

  def update
    party.update(attributes)
    render 'show'
  end

  def destroy
    party.destroy
    render 'index'
  end

  def show
    party
  end

  def index
    @parties = Party.where(user_id: user.id)
  end

  private

  def attributes
    params.require(:party).permit(:date, :title)
  end

  def user
    @user ||= User.find(params[:user_id])
  end

  def party
    @party ||= Party.find(params[:id])
  end
end

app/controllers/reservation_controller.rb
class ReservationController < ApplicationController
  before_action :authenticate_user!
  before_action :party

  def create
    @reservation = Reservation.create(
      user: current_user, wish_list_item: wish_list_item)
    render "party/show"
  end

  def destroy
    reservation && reservation.delete
    render "party/show"
  end

  private

  def attributes
    @attributes ||= params
      .require(:reservation)
      .permit(:user_id, :wish_list_item_id, :party_id)
  end

  def reservation
    @reservation ||= Reservation.where(
      user_id: current_user.id,
      wish_list_item_id: attributes[:wish_list_item_id]
    ).first
  end

  def party
    @party ||= Party.find(attributes[:party_id])
  end

  def wish_list_item
    @wish_list_item ||= WishListItem.find(attributes[:wish_list_item_id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.create(attributes)
    render 'show'
  end

  def new
  end

  def update
    user.update(attributes)
    render 'show'
  end

  def destroy
    user.destroy
  end

  def show
    user
    parties
  end

  def index
    @users = User.all
  end

  private

  def attributes
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

  def user
    @user ||= User.find(params[:id])
  end

  def parties
    @parties ||= if search_string && !search_string.empty?
                   Party.all.select do |party|
                     party.title.downcase.include?(search_string) ||
                     party.user.full_name.downcase.include?(search_string)
                   end
                 else
                   []
                 end
  end

  def search_string
    params[:search].downcase if params[:search]
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    permitted_params =
      devise_parameter_sanitizer.instance_variable_get(:@permitted)[:sign_up]
    permitted_params << :first_name
    permitted_params << :last_name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/party_helper.rb
module PartyHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<% if user_signed_in? %>
  <%= link_to user_path current_user do %>
    <div>
      Dein Profil
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Birthday</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="header-elements"> </div>
        <% if user_signed_in? %>
          <%= link_to 'Ausloggen', destroy_user_session_path, :method => :delete, :class=>"header-elements" %>
          <%= link_to 'Account', edit_user_registration_path, :class=>"header-elements" %>
          <%= link_to 'Profile', user_path(current_user), :class=>"header-elements" %>
        <% else %>
          <%= link_to 'Einloggen', new_user_session_path, :class=>"header-elements" %>
          <%= link_to 'Registrieren', new_user_registration_path, :class=>"header-elements" %>
        <% end %>
      </div>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/party/create.html.erb
<h1>Party#create</h1>
<p>Find me in app/views/party/create.html.erb</p>

app/views/party/destroy.html.erb
<h1>Party#destroy</h1>
<p>Find me in app/views/party/destroy.html.erb</p>

app/views/party/index.html.erb
<h1>Party#index</h1>
<p>Find me in app/views/party/index.html.erb</p>

app/views/party/show.html.erb
<% if user_signed_in? %>
  <%= link_to 'Zurück', user_path(id: current_user.id) %>
<% end %>

<h1> <%= @party.title %> </h1>

<% if user_signed_in? %>
  <% if @party.on_guest_list?(current_user) %>

  <% else %>
    <%= form_for :guest, :url => { :controller => :guest, :action => "create"}, :html => { :method => :post, } do |f| %>
          <%= f.hidden_field :party_id, :value => @party.id, :user_id => current_user.id %>
          <div class="actions">
            <%= f.submit "Mich auf Gästeliste setzen" %>
          </div>
          <p>
            Wer auf der Gästeliste eingetragen ist kann Wünsche sehen und reservieren. Dies soll vermeiden, dass Dinge doppelt verschenkt werden.
          </p>
        <% end %>
  <% end %>
<% else %>
  <h2>Info</h2>
  <p>
    Bitte <%= link_to 'registrieren', new_user_registration_path %> Sie sich oder <%= link_to 'loggen sich ein', new_user_session_path %>. Im Anschluss können Sie der Gästeliste beirtreten und sehen die Geburtstagswünsche, welche dann reserviert werden können.
  </p>
<% end %>

<% if user_signed_in? && @party.on_guest_list?(current_user) %>
  <h2> Meine Wunschliste </h2>
  <% @party.wish_list.each.with_index do |wish, i| %>
    <%if !wish.reserved? || (user_signed_in? && wish.reserved_by == current_user) %>
      <div class="wish_container <%= i > 0 ? 'further-wish' : '' %>">
        <h3> <%= wish.name %> </h3>
        <img class="wish--image" src=<%= wish.img_url %> />
        <p>
          Info: <%= wish.price.to_s.split('.').join(',') %> € bei <%= wish.location %>
        </p>

        <% if user_signed_in? %>
          <% unless wish.reserved? %>
            <%= form_for :reservation, :url => { :controller => :reservation, :action => :create }, :html => { :method => :post, } do |f| %>
              <%= f.hidden_field :party_id, :value => @party.id %>
              <%= f.hidden_field :wish_list_item_id, :value => wish.id %>

              <div class="actions">
                <%= f.submit "Will ich schenken" %>
              </div>
            <% end %>
          <% end %>

          <%if wish.reserved? && wish.reserved_by == current_user %>
            <%= form_for :reservation, :url => { :controller => :reservation, :action => :destroy }, :html => { :method => :delete, } do |f| %>
              <%= f.hidden_field :party_id, :value => @party.id %>
              <%= f.hidden_field :wish_list_item_id, :value => wish.id %>

              <div class="actions">
                <%= f.submit "Will ich doch nicht schenken" %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
<% else %>

<% end %>

app/views/party/update.html.erb
<h1>Party#update</h1>
<p>Find me in app/views/party/update.html.erb</p>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/delete.html.erb
<h1>User#delete</h1>
<p>Find me in app/views/user/delete.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>

<h2>
  Zur Zeit <%= @user.parties.count == 1 ? 'ist' : 'sind' %> <%= @user.parties.count == 0 ? 'keine' : @user.parties.count %> <%= @user.parties.count == 1 ? 'Feier' : 'Feiern' %> geplant.
</h2>
<ul>
  <% @user.parties.each do |party| %>
    <li>
      <%= link_to "#{party.title}", party_path(id: party.id) %>
    </li>
  <% end %>
</ul>

<h2>Zur Zeit hast du dich bei <%= @user.on_guest_list.count == 0 ? 'keiner' : @user.on_guest_list.count %> <%= @user.on_guest_list.count < 2 ? 'Feier' : 'Feiern' %> registriert. </h2>
<ul>
  <% @user.on_guest_list.each do |guest_relation| %>
    <li>
      <%= link_to "Feier \"#{guest_relation.party.title}\" von #{guest_relation.party.user.full_name}", party_path(id: guest_relation.party.id) %>
    </li>
  <% end %>
</ul>

<h2> Finde eine Feier </h2>
<p> Suche nach Namen oder dem Motto/Titel der Feier </p>
<%= form_tag user_path(id: current_user.id), :method => :get do %>
  <%= text_field_tag :search, params[:search], :id => 'search_field' %>
  <%= submit_tag "Suche", :name => nil %>
<% end %>

<ul>
  <% @parties.each do |party| %>
    <li>
      <%= link_to "#{party.title} von #{party.user.full_name}", party_path(id: party.id) %>
      <%= form_for :guest, :url => { :controller => :guest, :action => "create", party_id: party.id, user_id: current_user.id }, :html => { :method => :post, } do |f| %>

        <div class="actions">
          <%= f.submit "In Gästeliste eintragen" %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>